"""v1.0.0

Revision ID: 5bb08a245542
Revises:
Create Date: 2025-01-22 19:51:39.058291

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5bb08a245542"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "product",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("articul", sa.String(), nullable=False),
        sa.Column("name", sa.String(length=300), nullable=False),
        sa.Column("price", sa.Integer(), nullable=False),
        sa.Column("rating", sa.Float(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("is_tracking", sa.Boolean(), nullable=False),
        sa.CheckConstraint("price > 1", name="check_price_min"),
        sa.CheckConstraint("quantity >= 0", name="check_quantity_min"),
        sa.CheckConstraint("rating <= 5.0", name="check_rating_max"),
        sa.CheckConstraint("rating >= 0.0", name="check_rating_min"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("articul"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "user",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("email", sa.String(length=321), nullable=False),
        sa.Column("password", sa.LargeBinary(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("name"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user")
    op.drop_table("product")
    # ### end Alembic commands ###
